// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/AlfariziYasir/transactions/services/order/internal/core/model"
	mock "github.com/stretchr/testify/mock"
)

// InboxRepo is an autogenerated mock type for the InboxRepo type
type InboxRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, inbox
func (_m *InboxRepo) Create(ctx context.Context, inbox *model.Inbox) (bool, error) {
	ret := _m.Called(ctx, inbox)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Inbox) (bool, error)); ok {
		return rf(ctx, inbox)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Inbox) bool); ok {
		r0 = rf(ctx, inbox)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Inbox) error); ok {
		r1 = rf(ctx, inbox)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInboxRepo creates a new instance of InboxRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInboxRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *InboxRepo {
	mock := &InboxRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
