// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/AlfariziYasir/transactions/services/order/internal/core/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepo is an autogenerated mock type for the OrderRepo type
type OrderRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, order
func (_m *OrderRepo) Create(ctx context.Context, order *model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBulk provides a mock function with given fields: ctx, columns, rows
func (_m *OrderRepo) CreateBulk(ctx context.Context, columns []string, rows [][]interface{}) error {
	ret := _m.Called(ctx, columns, rows)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, [][]interface{}) error); ok {
		r0 = rf(ctx, columns, rows)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *OrderRepo) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, filters, order
func (_m *OrderRepo) Get(ctx context.Context, filters map[string]interface{}, order *model.Order) error {
	ret := _m.Called(ctx, filters, order)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}, *model.Order) error); ok {
		r0 = rf(ctx, filters, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDetail provides a mock function with given fields: ctx, orderID
func (_m *OrderRepo) GetDetail(ctx context.Context, orderID string) ([]*model.OrderItem, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetDetail")
	}

	var r0 []*model.OrderItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.OrderItem, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.OrderItem); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OrderItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, limit, offset, req
func (_m *OrderRepo) List(ctx context.Context, limit uint64, offset uint64, req map[string]interface{}) ([]*model.Order, int, error) {
	ret := _m.Called(ctx, limit, offset, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Order
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, map[string]interface{}) ([]*model.Order, int, error)); ok {
		return rf(ctx, limit, offset, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, map[string]interface{}) []*model.Order); ok {
		r0 = rf(ctx, limit, offset, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64, map[string]interface{}) int); ok {
		r1 = rf(ctx, limit, offset, req)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64, uint64, map[string]interface{}) error); ok {
		r2 = rf(ctx, limit, offset, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *OrderRepo) Update(ctx context.Context, id string, data map[string]interface{}) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderRepo creates a new instance of OrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepo {
	mock := &OrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
