// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/AlfariziYasir/transactions/services/order/internal/core/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, orderID, userID
func (_m *OrderService) Cancel(ctx context.Context, orderID string, userID string) error {
	ret := _m.Called(ctx, orderID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orderID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *OrderService) Create(ctx context.Context, userID string, req *model.CreateOrderRequest) (*model.CreateOrderResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.CreateOrderRequest) (*model.CreateOrderResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.CreateOrderRequest) *model.CreateOrderResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.CreateOrderRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, userID, role, orderID
func (_m *OrderService) Get(ctx context.Context, userID string, role string, orderID string) (*model.OrderResponse, error) {
	ret := _m.Called(ctx, userID, role, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.OrderResponse, error)); ok {
		return rf(ctx, userID, role, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.OrderResponse); ok {
		r0 = rf(ctx, userID, role, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, role, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, userID, role, req
func (_m *OrderService) List(ctx context.Context, userID string, role string, req *model.ListRequest) ([]*model.OrderResponse, int, string, error) {
	ret := _m.Called(ctx, userID, role, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.OrderResponse
	var r1 int
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.ListRequest) ([]*model.OrderResponse, int, string, error)); ok {
		return rf(ctx, userID, role, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.ListRequest) []*model.OrderResponse); ok {
		r0 = rf(ctx, userID, role, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *model.ListRequest) int); ok {
		r1 = rf(ctx, userID, role, req)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, *model.ListRequest) string); ok {
		r2 = rf(ctx, userID, role, req)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string, *model.ListRequest) error); ok {
		r3 = rf(ctx, userID, role, req)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// Update provides a mock function with given fields: ctx, req
func (_m *OrderService) Update(ctx context.Context, req *model.UpdateStatusOrder) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UpdateStatusOrder) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
