// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/AlfariziYasir/transactions/services/order/internal/core/model"
	mock "github.com/stretchr/testify/mock"
)

// OutboxRepo is an autogenerated mock type for the OutboxRepo type
type OutboxRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, outbox
func (_m *OutboxRepo) Create(ctx context.Context, outbox *model.Outbox) error {
	ret := _m.Called(ctx, outbox)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Outbox) error); ok {
		r0 = rf(ctx, outbox)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, limit
func (_m *OutboxRepo) Get(ctx context.Context, limit uint64) ([]*model.Outbox, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []*model.Outbox
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]*model.Outbox, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []*model.Outbox); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Outbox)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *OutboxRepo) Update(ctx context.Context, id string, data map[string]interface{}) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOutboxRepo creates a new instance of OutboxRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxRepo {
	mock := &OutboxRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
