// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/order/order.proto

package order

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_UNSPECIFIED   OrderStatus = 0
	OrderStatus_PENDING       OrderStatus = 1
	OrderStatus_PAID          OrderStatus = 2
	OrderStatus_READY_TO_SHIP OrderStatus = 3
	OrderStatus_SHIPPED       OrderStatus = 4
	OrderStatus_DELIVERED     OrderStatus = 5
	OrderStatus_CANCELED      OrderStatus = 6
	OrderStatus_FAILED        OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "PENDING",
		2: "PAID",
		3: "READY_TO_SHIP",
		4: "SHIPPED",
		5: "DELIVERED",
		6: "CANCELED",
		7: "FAILED",
	}
	OrderStatus_value = map[string]int32{
		"UNSPECIFIED":   0,
		"PENDING":       1,
		"PAID":          2,
		"READY_TO_SHIP": 3,
		"SHIPPED":       4,
		"DELIVERED":     5,
		"CANCELED":      6,
		"FAILED":        7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_order_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_order_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalAmount     string                 `protobuf:"bytes,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Currency        string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          OrderStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`
	ShippingAddress string                 `protobuf:"bytes,6,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Items           []*OrderItem           `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt       *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_UNSPECIFIED
}

func (x *Order) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Subtotal      string                 `protobuf:"bytes,5,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderItem) GetSubtotal() string {
	if x != nil {
		return x.Subtotal
	}
	return ""
}

type CreateOrderReponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReponse) Reset() {
	*x = CreateOrderReponse{}
	mi := &file_proto_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReponse) ProtoMessage() {}

func (x *CreateOrderReponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReponse.ProtoReflect.Descriptor instead.
func (*CreateOrderReponse) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderReponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CreateOrderRequest struct {
	state           protoimpl.MessageState            `protogen:"open.v1"`
	Items           []*CreateOrderRequest_ItemRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	ShippingAddress string                            `protobuf:"bytes,2,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetItems() []*CreateOrderRequest_ItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetShippingAddress() string {
	if x != nil {
		return x.ShippingAddress
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderRequest) Reset() {
	*x = ListOrderRequest{}
	mi := &file_proto_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRequest) ProtoMessage() {}

func (x *ListOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRequest.ProtoReflect.Descriptor instead.
func (*ListOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrderRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrderRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListOrderRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_UNSPECIFIED
}

type ListOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderResponse) Reset() {
	*x = ListOrderResponse{}
	mi := &file_proto_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderResponse) ProtoMessage() {}

func (x *ListOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderResponse.ProtoReflect.Descriptor instead.
func (*ListOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrderResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrderResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListOrderResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_proto_order_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateOrderRequest_ItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest_ItemRequest) Reset() {
	*x = CreateOrderRequest_ItemRequest{}
	mi := &file_proto_order_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest_ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest_ItemRequest) ProtoMessage() {}

func (x *CreateOrderRequest_ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest_ItemRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest_ItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_order_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CreateOrderRequest_ItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrderRequest_ItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_proto_order_order_proto protoreflect.FileDescriptor

const file_proto_order_order_proto_rawDesc = "" +
	"\n" +
	"\x17proto/order/order.proto\x12\border.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\"\x88\x03\n" +
	"\x05Order\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x03R\x02id\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tB\x03\xe0A\x03R\x06userId\x12&\n" +
	"\ftotal_amount\x18\x03 \x01(\tB\x03\xe0A\x03R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.order.v1.OrderStatusB\x03\xe0A\x03R\x06status\x12)\n" +
	"\x10shipping_address\x18\x06 \x01(\tR\x0fshippingAddress\x12)\n" +
	"\x05items\x18\a \x03(\v2\x13.order.v1.OrderItemR\x05items\x12>\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAt\"\x9b\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x1a\n" +
	"\bsubtotal\x18\x05 \x01(\tR\bsubtotal\"/\n" +
	"\x12CreateOrderReponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xfb\x01\n" +
	"\x12CreateOrderRequest\x12K\n" +
	"\x05items\x18\x01 \x03(\v2(.order.v1.CreateOrderRequest.ItemRequestB\v\xe0A\x02\xfaB\x05\x92\x01\x02\b\x01R\x05items\x125\n" +
	"\x10shipping_address\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x05R\x0fshippingAddress\x1aa\n" +
	"\vItemRequest\x12*\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tB\v\xe0A\x02\xfaB\x05r\x03\xb0\x01\x01R\tproductId\x12&\n" +
	"\bquantity\x18\x02 \x01(\x05B\n" +
	"\xe0A\x02\xfaB\x04\x1a\x02 \x00R\bquantity\"9\n" +
	"\x0fGetOrderRequest\x12&\n" +
	"\border_id\x18\x01 \x01(\tB\v\xe0A\x02\xfaB\x05r\x03\xb0\x01\x01R\aorderId\"\x95\x01\n" +
	"\x10ListOrderRequest\x12'\n" +
	"\tpage_size\x18\x01 \x01(\x05B\n" +
	"\xe0A\x02\xfaB\x04\x1a\x02 \x00R\bpageSize\x12)\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\tpageToken\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.order.v1.OrderStatusR\x06status\"\x85\x01\n" +
	"\x11ListOrderResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order.v1.OrderR\x06orders\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"`\n" +
	"\x12CancelOrderRequest\x12&\n" +
	"\border_id\x18\x01 \x01(\tB\v\xe0A\x02\xfaB\x05r\x03\xb0\x01\x01R\aorderId\x12\"\n" +
	"\x06reason\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xfaB\x04r\x02\x10\x01R\x06reason*~\n" +
	"\vOrderStatus\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\b\n" +
	"\x04PAID\x10\x02\x12\x11\n" +
	"\rREADY_TO_SHIP\x10\x03\x12\v\n" +
	"\aSHIPPED\x10\x04\x12\r\n" +
	"\tDELIVERED\x10\x05\x12\f\n" +
	"\bCANCELED\x10\x06\x12\n" +
	"\n" +
	"\x06FAILED\x10\a2\xd8\x04\n" +
	"\fOrderService\x12\xa5\x01\n" +
	"\x06Create\x12\x1c.order.v1.CreateOrderRequest\x1a\x1c.order.v1.CreateOrderReponse\"_\x92AG\n" +
	"\x05Order\x12\x13Checkout Order Baru\x1a)begin order transaction. Status: PENDING.\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12l\n" +
	"\x03Get\x12\x19.order.v1.GetOrderRequest\x1a\x0f.order.v1.Order\"9\x92A\x19\n" +
	"\x05Order\x12\x10Get Detail Order\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/orders/{order_id}\x12x\n" +
	"\x04List\x12\x1a.order.v1.ListOrderRequest\x1a\x1b.order.v1.ListOrderResponse\"7\x92A\"\n" +
	"\fOrder Public\x12\x12list order history\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12\xb7\x01\n" +
	"\x06Cancel\x12\x1c.order.v1.CancelOrderRequest\x1a\x16.google.protobuf.Empty\"w\x92AM\n" +
	"\fOrder Public\x12\x0eCanceled Order\x1a-User can be cancel order when status pending.\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/orders/{order_id}/cancelB\xc8\x01\x92A\x8a\x01\x12Q\n" +
	"\x11Order Service API\x127management order service (Checkout, Tracking, History).2\x031.0Z#\n" +
	"!\n" +
	"\n" +
	"BearerAuth\x12\x13\b\x02\x1a\rAuthorization \x02b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00Z8github.com/AlfariziYasir/transactions/common/proto/orderb\x06proto3"

var (
	file_proto_order_order_proto_rawDescOnce sync.Once
	file_proto_order_order_proto_rawDescData []byte
)

func file_proto_order_order_proto_rawDescGZIP() []byte {
	file_proto_order_order_proto_rawDescOnce.Do(func() {
		file_proto_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_order_proto_rawDesc), len(file_proto_order_order_proto_rawDesc)))
	})
	return file_proto_order_order_proto_rawDescData
}

var file_proto_order_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_order_order_proto_goTypes = []any{
	(OrderStatus)(0),                       // 0: order.v1.OrderStatus
	(*Order)(nil),                          // 1: order.v1.Order
	(*OrderItem)(nil),                      // 2: order.v1.OrderItem
	(*CreateOrderReponse)(nil),             // 3: order.v1.CreateOrderReponse
	(*CreateOrderRequest)(nil),             // 4: order.v1.CreateOrderRequest
	(*GetOrderRequest)(nil),                // 5: order.v1.GetOrderRequest
	(*ListOrderRequest)(nil),               // 6: order.v1.ListOrderRequest
	(*ListOrderResponse)(nil),              // 7: order.v1.ListOrderResponse
	(*CancelOrderRequest)(nil),             // 8: order.v1.CancelOrderRequest
	(*CreateOrderRequest_ItemRequest)(nil), // 9: order.v1.CreateOrderRequest.ItemRequest
	(*timestamp.Timestamp)(nil),            // 10: google.protobuf.Timestamp
	(*empty.Empty)(nil),                    // 11: google.protobuf.Empty
}
var file_proto_order_order_proto_depIdxs = []int32{
	0,  // 0: order.v1.Order.status:type_name -> order.v1.OrderStatus
	2,  // 1: order.v1.Order.items:type_name -> order.v1.OrderItem
	10, // 2: order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: order.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 4: order.v1.CreateOrderRequest.items:type_name -> order.v1.CreateOrderRequest.ItemRequest
	0,  // 5: order.v1.ListOrderRequest.status:type_name -> order.v1.OrderStatus
	1,  // 6: order.v1.ListOrderResponse.orders:type_name -> order.v1.Order
	4,  // 7: order.v1.OrderService.Create:input_type -> order.v1.CreateOrderRequest
	5,  // 8: order.v1.OrderService.Get:input_type -> order.v1.GetOrderRequest
	6,  // 9: order.v1.OrderService.List:input_type -> order.v1.ListOrderRequest
	8,  // 10: order.v1.OrderService.Cancel:input_type -> order.v1.CancelOrderRequest
	3,  // 11: order.v1.OrderService.Create:output_type -> order.v1.CreateOrderReponse
	1,  // 12: order.v1.OrderService.Get:output_type -> order.v1.Order
	7,  // 13: order.v1.OrderService.List:output_type -> order.v1.ListOrderResponse
	11, // 14: order.v1.OrderService.Cancel:output_type -> google.protobuf.Empty
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_order_order_proto_init() }
func file_proto_order_order_proto_init() {
	if File_proto_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_order_proto_rawDesc), len(file_proto_order_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_order_proto_goTypes,
		DependencyIndexes: file_proto_order_order_proto_depIdxs,
		EnumInfos:         file_proto_order_order_proto_enumTypes,
		MessageInfos:      file_proto_order_order_proto_msgTypes,
	}.Build()
	File_proto_order_order_proto = out.File
	file_proto_order_order_proto_goTypes = nil
	file_proto_order_order_proto_depIdxs = nil
}
