// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/notification/notification.proto

package notification

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationChannel int32

const (
	NotificationChannel_EMAIL             NotificationChannel = 0
	NotificationChannel_SMS               NotificationChannel = 1
	NotificationChannel_PUSH_NOTIFICATION NotificationChannel = 2
)

// Enum value maps for NotificationChannel.
var (
	NotificationChannel_name = map[int32]string{
		0: "EMAIL",
		1: "SMS",
		2: "PUSH_NOTIFICATION",
	}
	NotificationChannel_value = map[string]int32{
		"EMAIL":             0,
		"SMS":               1,
		"PUSH_NOTIFICATION": 2,
	}
)

func (x NotificationChannel) Enum() *NotificationChannel {
	p := new(NotificationChannel)
	*p = x
	return p
}

func (x NotificationChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notification_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationChannel) Type() protoreflect.EnumType {
	return &file_proto_notification_notification_proto_enumTypes[0]
}

func (x NotificationChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationChannel.Descriptor instead.
func (NotificationChannel) EnumDescriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

type NotificationType int32

const (
	NotificationType_ORDER_CREATED NotificationType = 0
	NotificationType_ORDER_PAID    NotificationType = 1
	NotificationType_ORDER_FAILED  NotificationType = 2
	NotificationType_ORDER_SHIPPED NotificationType = 3
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "ORDER_CREATED",
		1: "ORDER_PAID",
		2: "ORDER_FAILED",
		3: "ORDER_SHIPPED",
	}
	NotificationType_value = map[string]int32{
		"ORDER_CREATED": 0,
		"ORDER_PAID":    1,
		"ORDER_FAILED":  2,
		"ORDER_SHIPPED": 3,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notification_notification_proto_enumTypes[1].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_proto_notification_notification_proto_enumTypes[1]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{1}
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     string                 `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel       NotificationChannel    `protobuf:"varint,3,opt,name=channel,proto3,enum=notification.v1.NotificationChannel" json:"channel,omitempty"`
	Type          NotificationType       `protobuf:"varint,4,opt,name=type,proto3,enum=notification.v1.NotificationType" json:"type,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,5,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_proto_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendNotificationRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_EMAIL
}

func (x *SendNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_ORDER_CREATED
}

func (x *SendNotificationRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	SentAt         *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_proto_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *SendNotificationResponse) GetSentAt() *timestamp.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

var File_proto_notification_notification_proto protoreflect.FileDescriptor

const file_proto_notification_notification_proto_rawDesc = "" +
	"\n" +
	"%proto/notification/notification.proto\x12\x0fnotification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x02\n" +
	"\x17SendNotificationRequest\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\tR\trecipient\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12>\n" +
	"\achannel\x18\x03 \x01(\x0e2$.notification.v1.NotificationChannelR\achannel\x125\n" +
	"\x04type\x18\x04 \x01(\x0e2!.notification.v1.NotificationTypeR\x04type\x12O\n" +
	"\apayload\x18\x05 \x03(\v25.notification.v1.SendNotificationRequest.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x01\n" +
	"\x18SendNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\x123\n" +
	"\asent_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt*@\n" +
	"\x13NotificationChannel\x12\t\n" +
	"\x05EMAIL\x10\x00\x12\a\n" +
	"\x03SMS\x10\x01\x12\x15\n" +
	"\x11PUSH_NOTIFICATION\x10\x02*Z\n" +
	"\x10NotificationType\x12\x11\n" +
	"\rORDER_CREATED\x10\x00\x12\x0e\n" +
	"\n" +
	"ORDER_PAID\x10\x01\x12\x10\n" +
	"\fORDER_FAILED\x10\x02\x12\x11\n" +
	"\rORDER_SHIPPED\x10\x032~\n" +
	"\x13NotificationService\x12g\n" +
	"\x10SendNotification\x12(.notification.v1.SendNotificationRequest\x1a).notification.v1.SendNotificationResponseBAZ?github.com/AlfariziYasir/transactions/common/proto/notificationb\x06proto3"

var (
	file_proto_notification_notification_proto_rawDescOnce sync.Once
	file_proto_notification_notification_proto_rawDescData []byte
)

func file_proto_notification_notification_proto_rawDescGZIP() []byte {
	file_proto_notification_notification_proto_rawDescOnce.Do(func() {
		file_proto_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_notification_proto_rawDesc), len(file_proto_notification_notification_proto_rawDesc)))
	})
	return file_proto_notification_notification_proto_rawDescData
}

var file_proto_notification_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_notification_notification_proto_goTypes = []any{
	(NotificationChannel)(0),         // 0: notification.v1.NotificationChannel
	(NotificationType)(0),            // 1: notification.v1.NotificationType
	(*SendNotificationRequest)(nil),  // 2: notification.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil), // 3: notification.v1.SendNotificationResponse
	nil,                              // 4: notification.v1.SendNotificationRequest.PayloadEntry
	(*timestamp.Timestamp)(nil),      // 5: google.protobuf.Timestamp
}
var file_proto_notification_notification_proto_depIdxs = []int32{
	0, // 0: notification.v1.SendNotificationRequest.channel:type_name -> notification.v1.NotificationChannel
	1, // 1: notification.v1.SendNotificationRequest.type:type_name -> notification.v1.NotificationType
	4, // 2: notification.v1.SendNotificationRequest.payload:type_name -> notification.v1.SendNotificationRequest.PayloadEntry
	5, // 3: notification.v1.SendNotificationResponse.sent_at:type_name -> google.protobuf.Timestamp
	2, // 4: notification.v1.NotificationService.SendNotification:input_type -> notification.v1.SendNotificationRequest
	3, // 5: notification.v1.NotificationService.SendNotification:output_type -> notification.v1.SendNotificationResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_notification_notification_proto_init() }
func file_proto_notification_notification_proto_init() {
	if File_proto_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_notification_proto_rawDesc), len(file_proto_notification_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_notification_proto_goTypes,
		DependencyIndexes: file_proto_notification_notification_proto_depIdxs,
		EnumInfos:         file_proto_notification_notification_proto_enumTypes,
		MessageInfos:      file_proto_notification_notification_proto_msgTypes,
	}.Build()
	File_proto_notification_notification_proto = out.File
	file_proto_notification_notification_proto_goTypes = nil
	file_proto_notification_notification_proto_depIdxs = nil
}
